### ISSUE TITLE
Undefined function `posix_kill()`

### ISSUE THREAD

**Issue by whoami15** [web3-php/cli#4]
OS: Windows 10
PHP version: PHP 8.1.1

I've encountered the following error after I ran `web3` for the second time, Did anyone encounter the same?

```php
Fatal error: Uncaught Error: Call to undefined function Web3\Cli\Guards\posix_kill() in C:\Users\User\AppData\Roaming\Composer\vendor\web3-php\cli\src\Guards\KillsExistingServers.php:24
Stack trace:
#0 C:\Users\User\AppData\Roaming\Composer\vendor\web3-php\cli\src\Factories\CommandFactory.php(49): Web3\Cli\Guards\KillsExistingServers->execute()
#1 C:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php(296): Web3\Cli\Factories\CommandFactory->Web3\Cli\Factories\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\Command\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\Users\User\AppData\Roaming\Composer\vendor\web3-php\cli\bin\web3(32): Symfony\Component\Console\Application->run()#6 C:\Users\User\AppData\Roaming\Composer\vendor\web3-php\cli\bin\web3(38): {closure}()
#7 {main}
  thrown in C:\Users\User\AppData\Roaming\Composer\vendor\web3-php\cli\src\Guards\KillsExistingServers.php on line 24
  ```
  
 KillsExistingServers.php Line 24
```php
@posix_kill((int) $processId, SIGQUIT);
```

**Comment by nunomaduro** [comment]
I don't think this project supports windows.
